# USED FOR DEVELOPMENT LOCALLY

services:
  testdb:
    image: postgis/postgis:13-3.3
    environment:
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testdb
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - testdb:/var/lib/postgresql/data
    restart: always

  adminer:
    image: wodby/adminer:latest
    ports:
      - '9000:9000'
    restart: always
    environment:
      ADMINER_DEFAULT_DB_NAME: testdb
      ADMINER_DEFAULT_DB_HOST: testdb
      ADMINER_DEFAULT_DB_DRIVER: pgsql

volumes:
  testdb:
